// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAocqlhR5NCoTOpUchpCWxX1TFTp48UR40',
    appId: '1:592132510298:web:76feb42b9fa338a858fe63',
    messagingSenderId: '592132510298',
    projectId: 'gachitayo-1af1d',
    authDomain: 'gachitayo-1af1d.firebaseapp.com',
    storageBucket: 'gachitayo-1af1d.firebasestorage.app',
    measurementId: 'G-HNXB95NPFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXxcYPCa0X9Wy4fM0td85xfPCy5KJ5yPI',
    appId: '1:592132510298:android:ee36bae8414b135458fe63',
    messagingSenderId: '592132510298',
    projectId: 'gachitayo-1af1d',
    storageBucket: 'gachitayo-1af1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzWYsxWPx4TMkd34P2jI8w2-2TbiPIxfA',
    appId: '1:592132510298:ios:0a17463301b05cdb58fe63',
    messagingSenderId: '592132510298',
    projectId: 'gachitayo-1af1d',
    storageBucket: 'gachitayo-1af1d.firebasestorage.app',
    androidClientId: '592132510298-5ashdclh3bqbceqgi9db8hmh9kcb0llj.apps.googleusercontent.com',
    iosClientId: '592132510298-kn7k8c5plk49sebn5c6tfk3k5qqris7a.apps.googleusercontent.com',
    iosBundleId: 'com.example.app2Client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzWYsxWPx4TMkd34P2jI8w2-2TbiPIxfA',
    appId: '1:592132510298:ios:0a17463301b05cdb58fe63',
    messagingSenderId: '592132510298',
    projectId: 'gachitayo-1af1d',
    storageBucket: 'gachitayo-1af1d.firebasestorage.app',
    androidClientId: '592132510298-5ashdclh3bqbceqgi9db8hmh9kcb0llj.apps.googleusercontent.com',
    iosClientId: '592132510298-kn7k8c5plk49sebn5c6tfk3k5qqris7a.apps.googleusercontent.com',
    iosBundleId: 'com.example.app2Client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAocqlhR5NCoTOpUchpCWxX1TFTp48UR40',
    appId: '1:592132510298:web:0ff55e596af2341158fe63',
    messagingSenderId: '592132510298',
    projectId: 'gachitayo-1af1d',
    authDomain: 'gachitayo-1af1d.firebaseapp.com',
    storageBucket: 'gachitayo-1af1d.firebasestorage.app',
    measurementId: 'G-T93PYV31TC',
  );

}